### ISSUE TITLE
`pdf2pdfa` | 'Syntax Error: loop in Resources (numObj: 1519)'

### ISSUE THREAD

**Issue by Ricky-Tigg** [uroesch/pdftools#66]
```
$ pdf2pdfa -V | head -1
pdf2pdfa v0.2.0
$ pdf2pdfa -h
Missing dependency 'pdftops'
Please install first!
$ dnf -q --available list pdftops
Error: No matching Packages to list
```
Hello. I suspect that by _dependency_, which is referring to _package_, you meant _binary file_. Checking.
```
$ pdftops
bash: pdftops: command not found...
Install package 'poppler-utils' to provide command 'pdftops'? [N/y] 
```
I am correct. Then the correct dependency was _poppler-utils_. Unless the following was installed by default in Fedora Desktop I would not have known. 
```
$ dnf rq --installed --qf '%{version} | %{summary} | %{license}' PackageKit-command-not-found
1.2.6 | Ask the user to install command line programs automatically | GPLv2+ and LGPLv2+
```
Test:
```
$ file -b 0.pdf
PDF document, version 1.6
$ pdf2pdfa -S -l 3 0.pdf
Syntax Error: loop in Resources (numObj: 1519)
```

**Comment by uroesch** [comment]
Thanks for the bug report Ricky-Tigg. Could you please send the output by running bash with `xtrace` set.  e.g. 

```
bash -x pdf2pdfa -S -l 3 0.pdf
```

The error you encounter could well be from the `ghostscript` command so I want to make sure the problem is not an issue with the wrapper coder from `pdf2pdfa`. 

Note: I'm going on vacation and will not be able to look into this matter in a timely manner. As I will be off the air  for an extended period of time. 

As for the dependency message that you encountered. I may add a hint that a binary files is meant to be installed.  Please also understand that Fedora or Red Hat based systems have different names for various packages compared to say Debian systems.  Checking and suggesting package names for each and every distro flavor out there is out of scope for such a basic wrapper.

cheers

**Comment by Ricky-Tigg** [comment]
System rebooted since your comment. **Issue not reproduced**.

_README.adoc_ file:
```
Convert pdf file `sample.pdf` to a PDF/A-2 named `sample_a.pdf`
pdf2pdfa sample.pdf
```
Unlike that description, the present source file's name _0.pdf_ was converted into __a.pdf_, not  _0_a.pdf_, therefore **ignoring the original name**.

Then _1.6_, the **highest PDF version supported by LibreOffice** is compatible for conversion into PDF v. 1.7 /A3.
```
$ file -b _a.pdf 
PDF document, version 1.7, 1 pages
```
Who knows what makes the _Canonical_ company to be known as being so good at keeping components so significantly outdated. _ISO 32000-2:2020_ is likely unknown yet to it. So it won't be seen soon a PDF v. 2.0 support implemented in LibreOffice suite.

There are surprises in respect to conversions since the **conformance levels** you implemented are non-documented. For PDF/A3, among _a_, _b_ and _u_, i guessed _b_ would be implemented as it is the one that LibreOffice supports. And so it is; discovered with a third-party tool. I assumed it could be discovered with your tool however the output here is empty.
```
$ pdfmeta -V _a.pdf 
$
```

**Comment by Ricky-Tigg** [comment]
### Case 1 | **issue not reproduced** | empty PDF source document

_README.adoc_ file:
```
Convert pdf file `sample.pdf` to a PDF/A-2 named `sample_a.pdf`
pdf2pdfa sample.pdf
```
Unlike the above description, the present source file's name _0.pdf_ was converted into __a.pdf_, not  _0_a.pdf_, therefore **ignoring the original name**.

Then _1.6_, the **highest PDF version supported by LibreOffice** is compatible for conversion into PDF v. 1.7 /A3.
```
$ file -b _a.pdf 
PDF document, version 1.7, 1 pages
```
Who knows what makes the _Canonical_ company to be known as being so good at keeping components so significantly outdated. _ISO 32000-2:2020_ is likely unknown yet to it. It won't be seen soon a PDF v. 2.0 support implemented in LibreOffice suite.

There are surprises in respect to conversions since the **conformance levels** you implemented are not documented. For PDF/A3, among _a_, _b_ and _u_, I guessed _b_ would be implemented as it is the one that LibreOffice implemented. And so it is; discovered with a third-party tool. I assumed it could be discovered with your tool however the following output is empty.
```
$ pdfmeta -V _a.pdf 
$
```
### Case 2 | **issue reproduced** | same non-empty PDF source document
Note: `file -b` unable to report the source document's number of pages which indicates an issue in the version of _file_ package used, **v. 5.44**.
```
$ bash -x pdf2pdfa -S -l 3 ../0.pdf
+ set -o errexit
+ set -o nounset
+ set -o pipefail
+ declare -r SCRIPT=pdf2pdfa
+ declare -r VERSION=0.2.0
+ declare -r 'AUTHOR=Urs Roesch <github@bun.ch>'
+ declare -r LICENSE=MIT
+ declare SUFFIX=_a
+ PDF_FILES=()
+ declare -a PDF_FILES
+ declare -i ARCHIVE_LEVEL=2
+ declare -i COMPATIBILITY_POLICY=1
+ declare -u COLOR_MODEL=rgb
+ DEPENDENCIES=('gs' 'pdftops')
+ declare -a DEPENDENCIES
+ check_dependencies
+ for dependency in ${DEPENDENCIES[@]}
+ command -v gs
+ for dependency in ${DEPENDENCIES[@]}
+ command -v pdftops
+ parse_options -S -l 3 ../0.pdf
+ [[ 4 -eq 0 ]]
+ [[ 4 -gt 0 ]]
+ case $1 in
+ COMPATIBILITY_POLICY=2
+ shift
+ [[ 3 -gt 0 ]]
+ case $1 in
+ shift
+ ARCHIVE_LEVEL=3
+ shift
+ [[ 1 -gt 0 ]]
+ case $1 in
+ PDF_FILES+=("${1}")
+ shift
+ [[ 0 -gt 0 ]]
+ convert_pdf
+ for pdf_original in "${PDF_FILES[@]}"
+ file ../0.pdf
+ grep -q -w PDF
+ to_pdfa ../0.pdf
+ local pdf_document=../0.pdf
+ shift
++ to_postscript ../0.pdf
++ local pdf_document=../0.pdf
++ shift
+++ mktemp
++ local ps_document=/tmp/tmp.O8bQvuBTFs
++ pdftops ../0.pdf /tmp/tmp.O8bQvuBTFs
Syntax Error: loop in Resources (numObj: 1519)
```

**Comment by Ricky-Tigg** [comment]
Closing while being indefinitely left open in an **non-fixed** state, rather than keeping it being in such a state, which would not be healthy for you. Solely leaving open those issues that I am confident the owner of the project has the developer's skill to fix it, which is fair. Good luck though.
